import React, { useState } from "react";
import { db, auth } from "../../firebase";

async function AiPhoto(imagePrompt, email) {
    console.log('AI PHOTO HERE')
    let photoLocation = "";
    // let imagePrompt = imagePrompt;
    // let email = email;
    //   const [words, setWords] = useState("");
    //   const [count, setCount] = useState(0);
    // const [imageURL, setImageURL] = useState(null);

    const user = auth.currentUser;

    //   async function fetchImage(imagePrompt, email) {
        // setWords(imagePrompt)
        console.log(imagePrompt, email)
        try {
      const response = await fetch("http://localhost:3002/image-generation", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ message: imagePrompt, user: email }),
      });
      const data = await response.json();
    //   setImageURL(data.data);

      photoLocation = data.photoName;

      const userInfoRef = await db
        .collection("users")
        .doc(`${auth.currentUser.email}`);
      userInfoRef.update({ photo: photoLocation });
    } catch (error) {
      console.error(error);
        }
    return photoLocation;
//   }

  //   const handleSubmit = (e) => {
  //     e.preventDefault();
  //     fetchImage();
  //   };

  //   return (
  //     <>
  //       <div>
  //         <h3>Enter 6 words to generate an image</h3>
  //         <input
  //           type="text"
  //           value={words}
  //           onChange={handleChange}
  //           placeholder="6 words separated by spaces"
  //         />
  //         <p>Words Count: {count}</p>
  //         {count >= 6 ? <button onClick={handleSubmit}>Submit</button> : null}
  //         {imageURL ? <img src={imageURL} alt="Generated by Dall-E 2" /> : null}
  //       </div>
  //     </>
  //   );
};
export default AiPhoto;
